on:
    push:
      branches:
        - master

name: 🚀 Deploy website on master push
jobs:
    web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
    
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.tailorsdev.com
          username: gestion@tailorsdev.com
          password: WmV1K4tOGwRg
          protocol: ftps
